controllers/AuthController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\controllers;

use app\models\LoginForm;
use app\models\RegisterForm;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;

/**
 * Description of AuthController
 *
 * @author user
 */
class AuthController extends Controller {
    
    public function behaviors() {
        return [
          'access' => [
              'class' => AccessControl::className(),
              'only' => ['login', 'register'],
              'rules' => [
                  [
                      'allow' => true,
                      'roles' => ['?'],
                  ]
              ]
          ]
        ];
        }
    
    public function actionLogin() {
    $model = new LoginForm;
    if ($model->load(Yii::$app->request->post()) && $model->enter()) {
        return $this->redirect(['feed/index']);
    }
        return $this->render('login', compact('model'));
    }
    
    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->redirect(['auth/login']);
    }
    
    public function actionRegister() {
        $model = new RegisterForm;
        if(Yii::$app->request->isPost) {
            if($model->load(Yii::$app->request->post()) && $model->register()) {
                return $this->redirect(Url::to(['auth/login']));
            }
        }
        
        return $this->render('register', compact('model'));
        
    }
}

controllers/FeedController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\controllers;

use app\models\Photo;
use app\models\Relation;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Description of FeedController
 *
 * @author user
 */
class FeedController extends Controller {
       public function behaviors() {
        return [
          'access' => [
              'class' => AccessControl::className(),
              'only' => ['index', 'search'],
              'rules' => [
                  [
                      'allow' => true,
                      'roles' => ['@'],
                  ]
              ]
          ]
        ];
        }
        
    public function actionIndex() {
       $user = Yii::$app->user->identity->id;
       if(Relation::getCountMySubscribe() < 5) { // если количество на кого подписан меньше чем 5, то будем предлагать ему подписаться
           $recommend = User::getRecommendUsers();
       }
       $relations = Relation::find()->where(['first_id' => $user, 'type' => 1])->all();
       $arr = []; // создаем массив для фотографий
       for($i = 0; $i < count($relations); $i++) { // Получаем связи для текущего пользователя
           $photos = Photo::find()->where(['user_id' => $relations[$i]->second_id])->orderBy(['date' => SORT_DESC])->all();
           foreach($photos as $pho) { 
               array_push($arr, $pho); // в цикле проходим каждую фотку и добавляем ее в массив для фоток
           }
       }
       
       rsort($arr); // делаем обратную сортировку, чтобы лента была начиная с последней загруженной фотки 
       
        return $this->render('index', compact('arr', 'recommend'));
    }
    
    public function actionSearch($q) {
        $users = User::find()->where(['like', 'login', $q])->all();
       
        foreach($users as $user){
        $relations = Relation::find()->where(['first_id' => Yii::$app->user->identity->id, 'second_id' => $user->id])->all();
        }
         if(Yii::$app->request->post('Subscribe')) { // Если пользователь нажал кнопку подписки
             if(Relation::subscribe(Yii::$app->request->post('Subscribe'))) {
                 return $this->redirect(['/' . Yii::$app->request->post('Subscribe')]);
             }
         }
          if(Yii::$app->request->post('Unsubscribe')) { // Если пользователь нажал кнопку отписки
        if(Relation::unsubscribe(Yii::$app->request->post('Unsubscribe'))) {
            return $this->refresh();
        }
         }
        return $this->render('search', compact('users', 'relations'));
    }
    }

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Gistogram',
        'brandUrl' => ['/' . Yii::$app->user->identity->id],
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
           ['label' => 'Пользователи', 'url' => ['/admin/user']],
           ['label' => 'Фотографии', 'url' => ['/admin/photo']],
            ['label' => 'Комментарии', 'url' => ['/admin/comment']]
            
        ],
    ]);
    ?>
    <?php
    NavBar::end();
    ?>
   
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::a("Igor Volokitin", ['/21']) ?> <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Gistogram',
        'brandUrl' => ['/' . Yii::$app->user->identity->id],
        'options' => [
            'class' => 'navbar-default navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
           Yii::$app->user->identity->admin ? (['label' => 'Администрирование', 'url' => ['/admin/']]) : '' ,
            !Yii::$app->user->isGuest ? (['label' => 'Лента', 'url' => ['/feed/index']]) : '',
            !Yii::$app->user->isGuest ? (
                    ['label' => 'Профиль', 'url' => ['/' . Yii::$app->user->identity->id]]) : '',
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/auth/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/auth/logout'], 'post')
                . Html::submitButton(
                    'Выйти (' . Yii::$app->user->identity->login . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    ?>
    <div class="form-group row">
 <?= !Yii::$app->user->isGuest ? Html::img(Yii::getAlias('@web') . '/images/bell-unactive.png', ['class' => 'bell-unactive']) : '' ?>         

  <div class="col-md-3">
      <form method = "get" action = "<?= Url::to(['feed/search']) ?>">
    <input class="form-control" name = 'q' type="search" placeholder="Поиск пользователя" id="example-search-input">
      </form>
  </div>
   </div>
    <?php
    NavBar::end();
    ?>
   
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>
<?php
$this->registerJs(
  "$(document).on('ready', function() {  
    $('.bell-unactive').click(function(e){
       $('#pModal').modal('show')
                  .find('.content')
                  .load('/profile/notify');  
   });
});
");

 yii\bootstrap\Modal::begin([
    'header' => 'Последние понравившиеся',
    'id'=>'pModal',
]);
echo '<div class = "content"></div>';
 yii\bootstrap\Modal::end();
 ?>
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::a("Igor Volokitin", ['/1']) ?> <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>