models/Like.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * Description of Like
 *
 * @author user
 */
class Like extends ActiveRecord {
    public static function tableName() {
        return 'likes';
    }
    
    public function getPhoto() {
        return $this->hasOne(Photo::className(), ['id' => 'photo_id']);
    }
    
    public static function like($id) {
        $like = new Like();
        /* проверка, если этот пользователь лайк уже ставил,
         * чтобы лайк не повторялся больше и в базу не записывался тот же лайк повторно  */
        $getlike = Like::find()->where(['photo_id' => $id, 'user_id' => Yii::$app->user->identity->id])->all();
        if(empty($getlike)) {
        $like->user_id = Yii::$app->user->identity->id;
        $like->photo_id = $id;
        return $like->save();
        }
    }
    public static function unlike($id) {
        $like = Like::find()->where(['user_id' => Yii::$app->user->identity->id, 'photo_id' => $id])->one();
        return $like->delete();
    }
    
    public function getUser() {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}

controllers/FeedController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\controllers;

use app\models\Photo;
use app\models\Relation;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Description of FeedController
 *
 * @author user
 */
class FeedController extends Controller {
       public function behaviors() {
        return [
          'access' => [
              'class' => AccessControl::className(),
              'only' => ['index', 'search'],
              'rules' => [
                  [
                      'allow' => true,
                      'roles' => ['@'],
                  ]
              ]
          ]
        ];
        }
        
    public function actionIndex() {
       $user = Yii::$app->user->identity->id;
       if(Relation::getCountMySubscribe() < 5) { // если количество на кого подписан меньше чем 5, то будем предлагать ему подписаться
           $recommend = User::getRecommendUsers();
       }
       $relations = Relation::find()->where(['first_id' => $user, 'type' => 1])->all();
       $arr = []; // создаем массив для фотографий
       for($i = 0; $i < count($relations); $i++) { // Получаем связи для текущего пользователя
           $photos = Photo::find()->where(['user_id' => $relations[$i]->second_id])->orderBy(['date' => SORT_DESC])->all();
           foreach($photos as $pho) { 
               array_push($arr, $pho); // в цикле проходим каждую фотку и добавляем ее в массив для фоток
           }
       }
       
       rsort($arr); // делаем обратную сортировку, чтобы лента была начиная с последней загруженной фотки 
       
        return $this->render('index', compact('arr', 'recommend'));
    }
    
    public function actionSearch($q) {
        $users = User::find()->where(['like', 'login', $q])->all();
       
        foreach($users as $user){
        $relations = Relation::find()->where(['first_id' => Yii::$app->user->identity->id, 'second_id' => $user->id])->all();
        }
         if(Yii::$app->request->post('Subscribe')) { // Если пользователь нажал кнопку подписки
             if(Relation::subscribe(Yii::$app->request->post('Subscribe'))) {
                 return $this->redirect(['/' . Yii::$app->request->post('Subscribe')]);
             }
         }
          if(Yii::$app->request->post('Unsubscribe')) { // Если пользователь нажал кнопку отписки
        if(Relation::unsubscribe(Yii::$app->request->post('Unsubscribe'))) {
            return $this->refresh();
        }
         }
        return $this->render('search', compact('users', 'relations'));
    }
    }

views/feed/index.php
<?php

use yii\helpers\Html;

$this->title = 'Лента';
$imgsdir = Yii::getAlias('@web') . '/images/';
?>

<?php if(!empty($recommend)): ?>
<center><h4>Возможно, Вам будут интересны следующие аккаунты:</h4></center>
<center>
<?php foreach ($recommend as $user): ?>
<?php if($user->id != Yii::$app->user->identity->id): ?>
        <div class ='col-md-4'>
        <div class="panel panel-default table-responsive my-panel-profile">
        <div class="panel-heading">
            <?= Html::img(Yii::getAlias('@web') . '/uploads/' . $user->avatar, ['class' => 'avatar-feed']) ?>&nbsp;&nbsp;<strong><?= Html::a(Html::encode($user->login), ['/' . $user->id])?></strong>
            <?php if($user->verified == 1): ?>
            <?= Html::img(Yii::getAlias('@web') . '/images/checkmark.png', ['width' => '15px', 'title' => 'Подтвержденная страница']) ?>
            <?php endif; ?>
            </div>
</div>
        </div>
    <?php endif; ?>
    </center>
<?php endforeach; ?>
<?php endif; ?>

<hr>

<?php
foreach($arr as $array): ?>

<?php 
$location = (!empty($array->location)) ? $array->location : null;
?>

<center>
        <div class="panel panel-default table-responsive my-panel">
        <div class="panel-heading"><?= Html::img(Yii::getAlias('@web') . '/uploads/' . $array->user->avatar, ['class' => 'avatar-feed']) ?>&nbsp;&nbsp;<strong><?= Html::a(Html::encode($array->user->login), ['/' . $array->user->id]) ?></strong>
            <hr>
             <?php if($location): ?>
            <strong><?= Html::img(Yii::getAlias('@web' . '/images/location.png'), ['title' => 'Местоположение']) . '&nbsp;' . Html::encode($location)  ?></strong> <br>
      <?php endif; ?>
         <?= Html::img($imgsdir . 'eye.png', ['title' => 'Количество просмотров', 'width' => '20px']); ?> <?= $array->views ?>&nbsp;
         <?= Html::img($imgsdir . 'comments.png', ['title' => 'Комментарии', 'width' => '15px']); ?> <?= $array->getComments()->count() ?>&nbsp;
          <?php if($array->checkIfLiked($array->id)): ?>
           <?= Html::img($imgsdir . 'like-active.png', ['title' => 'Вы оценили публикацию ' . $array->user->login, 'width' => '15px']); ?> <?= $array->getLikes()->count() ?>&nbsp;
         <?php else: ?>
            <?= Html::button(Html::img(Yii::getAlias("@web") . '/images/like-unactive.png', ['width' => '20px', 'class' => 'like-btn-feed', 'data-id' => $array->id]), ['class' => 'floating-like-feed', 'name' => 'like', 'data-id' => $array->id]) ?>
         <?= Html::img($imgsdir . 'like-unactive.png', ['title' => 'Количество людей, каким понравилась публикация', 'width' => '15px']); ?> <?= $array->getLikes()->count() ?>&nbsp;
          
               <?php endif; ?>
        
         
        </div>
           
            <div class="panel-body"><?= Html::a(Html::img(Yii::getAlias('@web') . '/uploads/' . $array->photo, ['class' => 'imgmax-feed']), ['profile/view/' . $array->id], ['data-id' => $array->id]) ?></div>
 
  <div class="panel-footer">
          <?php if(!empty($array->description)): ?>
      <?= Html::encode($array->description) ?>
  </div>

  <?php endif; ?>
</div>
</center>
    <?php endforeach; ?>





    

views/feed/search.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>

<center>
    
    <?php foreach($users as $user): ?>
        <?php if($user->id != Yii::$app->user->identity->id): ?>
        <div class="panel panel-default table-responsive my-panel">
        <div class="panel-heading">
            <?= Html::img(Yii::getAlias('@web') . '/uploads/' . $user->avatar, ['class' => 'avatar-feed']) ?>&nbsp;&nbsp;<strong><?= Html::a(Html::encode($user->login), ['/' . $user->id])?></strong>
            <?php if($user->verified == 1): ?>
            <?= Html::img(Yii::getAlias('@web') . '/images/checkmark.png', ['width' => '15px', 'title' => 'Подтвержденная страница']) ?>
            <?php endif; ?>
            <hr><?= Html::encode($user->bio)?></div>
  <div class="panel-body"><?php foreach($user->photos as $key => $photos): ?>
        <?php if($key <= 5): // 6 фоток только достанем для одного результата поиска (с нуля ж) ?>
        <?= Html::img(Yii::getAlias("@web") . '/uploads/' . $photos->photo, ['class' => 'min-photo-search']) ?>
        <?php endif; ?>
            <?php endforeach; ?>
  </div>
</div>
    <?php endif; ?>
    <?php endforeach; ?>
    
</center>